### PR TITLE
fix(repo): Dart 3.19/3.22 support

### LINKED ISSUE #1959: Can't build flutter app on flutter SDK v3.22.2 and Dart v3.4.3 due to dependent package using deprecated textTheme property "bodyText1"
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

v7.2.1

### What happened?

Fails to build my flutter app

### Steps to reproduce

```bash
1. Create flutter app on flutter SDK version >3.19.0 that depends on stream_chat_flutter v7.2.1

2. Run `flutter run`

Expected: App builds successfully

Actual: App build fails with the following build output:
pub.dev/audio_video_progress_bar-0.11.0/lib/audio_video_progress_bar.dart:259:61: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
    final textStyle = timeLabelTextStyle ?? theme.textTheme.bodyText1;
                                                            ^^^^^^^^^
```

### Supporting info to reproduce

https://docs.flutter.dev/release/breaking-changes/3-19-deprecations

_No response_

### Relevant log output

```shell
pub.dev/audio_video_progress_bar-0.11.0/lib/audio_video_progress_bar.dart:259:61: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../flutter/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
    final textStyle = timeLabelTextStyle ?? theme.textTheme.bodyText1;
                                                            ^^^^^^^^^
```

### Flutter analyze output

_No response_

### Flutter doctor output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by deven98**
Restricts package to Flutter 3.19 onwards. Fixes #1959.

### CODE REVIEW

**Review by Brazol — APPROVED** [review]
LGTM

**Comment by alextarana** [comment]
#1967 fixes all issues for the correct merge of this pull request, please consider merging it here @deven98

File: packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager_desktop.dart [hunk 1]
```diff
@@ -1,11 +1,11 @@
-import 'package:dart_vlc/dart_vlc.dart';
+import 'package:media_kit/media_kit.dart';
 import 'package:stream_chat_flutter/src/video/vlc/vlc_manager.dart';
 
 /// The desktop implementation of [VlcManager]. It simply initializes VLC.
 class VlcManagerDesktop extends VlcManager {
   @override
   void initialize() {
-    DartVLC.initialize();
+    MediaKit.ensureInitialized();
```
Comment (Nash0x7E2) [inline packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager_desktop.dart:8]: Any reason for switching to MediaKit from VLC?

Comment (Nash0x7E2) [reply packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager_desktop.dart:8]: (Just personal curiosity)

**Review by Nash0x7E2 — APPROVED** [review]
Looks good!

File: packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager_desktop.dart (hunk 1 above)
Comment (alextarana) [reply packages/stream_chat_flutter/lib/src/video/vlc/vlc_manager_desktop.dart:8]: Mainly because DartVLC has an outdated package dependency which prevent its compatibility with dart 3.22 (and also 3.19).
On the other hand, DartVLC is marked as deprecated and replaced with MesiaKit on pub.dev
