### PR TITLE
fix: attachments upload when size exceeds

### LINKED ISSUE #371: Files Larger Than 20MB Can Still Be Sent and Become Permanently Stuck
**Describe the bug**
Attempting to attach a file larger than 20MB shows the error but allows the file to be sent.
Upload then subsequently fails and the failed file becomes stuck permanently, with no ability to remove.

**What package are you using? What version?**
v1.5.1 

**What platform is it about?**
- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Attach video larger than 20MB.
2. Dismiss warning message.
3. File attachment still exists and can be sent.
4. Send
5. Sending fails and becomes stuck in chat with no ability to remove.

**Expected behavior**
Do not allow attachments that are larger than the file size limit.

**Screenshots**
Screenshot_20210331-132550
Screenshot_20210331-132606

### PR DESCRIPTION
**Pull request by deven98**
Fixes #371

### CODE REVIEW

File: packages/stream_chat_flutter/lib/src/message_input.dart [hunk 1]
```diff
@@ -1988,8 +1989,6 @@ class MessageInputState extends State<MessageInput> {
       extraData: extraDataMap.isNotEmpty ? extraDataMap : null,
     );
 
-    _attachments[attachment.id] = attachment;
```
Comment (xsahil03x) [inline packages/stream_chat_flutter/lib/src/message_input.dart:1991]: I think we added the attachment at the start because the compression may take some time and we want to show it ASAP as the selected item in message input.

Comment (deven98) [reply packages/stream_chat_flutter/lib/src/message_input.dart:1991]: I think there's a a better way to do that. If we want to do this, let's also add a check at the end checking for file sizes.

**Review by xsahil03x — APPROVED** [review]
LGTM
