### PR TITLE
fix: user list error handling

### LINKED ISSUE #510: Cast Error on UserListView
**Describe the bug**
When using UserListView Widget it sometimes fails due to timeout or other network issues. When this happens non controlled exception is thrown with a wrong type:

**What package are you using? What version?**
  stream_chat_flutter: ^2.0.0-nullsafety.7

**What platform is it about?**
- [X] Android
- [X] iOS

**Expected behavior**
I would expect the widget to display a graceful error message asking the user to try again or something similar.

**Screenshots**
image

**Logs **
I/flutter (20486): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20486): The following _CastError was thrown building StreamBuilder<List<ListItem>>(dirty, state:
I/flutter (20486): _StreamBuilderBaseState<List<ListItem>, AsyncSnapshot<List<ListItem>>>#b02f6):
I/flutter (20486): type 'DioError' is not a subtype of type 'Error' in type cast
I/flutter (20486): 
I/flutter (20486): The relevant error-causing widget was:
I/flutter (20486):   UserListView
I/flutter (20486):   ****.dart:60:16
I/flutter (20486): 
I/flutter (20486): When the exception was thrown, this was the stack:
I/flutter (20486): #0      _UserListViewState.build.<anonymous closure> (package:stream_chat_flutter/src/user_list_view.dart:160:36)
I/flutter (20486): #1      UserListCoreState._buildListView.<anonymous closure> (package:stream_chat_flutter_core/src/user_list_core.dart:176:39)
I/flutter (20486): #2      StreamBuilder.build (package:flutter/src/widgets/async.dart:546:81)
I/flutter (20486): #3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124:48)
I/flutter (20486): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
I/flutter (20486): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
I/flutter (20486): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)

**Additional context**
Cannot reproduce directly as it happens from time to time, mostly related to network timeout, I guess.

### PR DESCRIPTION
**Pull request by imtoori**
fixes #510

### CODE REVIEW

File: packages/stream_chat_flutter/lib/src/user_list_view.dart [hunk 1]
```diff
@@ -194,12 +194,10 @@ class _UserListViewState extends State<UserListView>
...
       widget.sort?.any((e) => e.field == 'name' && e.direction == 1) ?? false;
 
-  Widget _buildError(Error error) {
-    print(error.stackTrace);
-
+  Widget _buildError(Object error) {
     var message = error.toString();
     if (error is DioError) {
-      final dioError = error as DioError;
+      final dioError = error;
```
Comment (xsahil03x) [inline packages/stream_chat_flutter/lib/src/user_list_view.dart:200]: we don't need to check for dio errors now instead, check for `StreamChatError.isRetriable`.

**Review by xsahil03x — CHANGES_REQUESTED** [review]
LGTM

**Review by xsahil03x — APPROVED** [review]
LGTM
