### PR TITLE
fix: channels bloc does not perform the call if pagination ended

### LINKED ISSUE #413: ChannelListView wont refresh automatically
**Describe the bug**
ChannelListView widget won't refresh automatically when new channel is added. I must reload the ChannelsBloc to get it query the new channels.

**What package are you using? What version?**
^1.5.3

**What platform is it about?**
- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Set up demo apps with login page, home page and channel list page
2. After we got autheticated on the login page, go to the channel list page
3. Add new channel, and the channel list still got the same state and list

**Expected behavior**
The channel list will refresh and updating the list whenever a channel ( which contain our member id )
 is added

**Logs **
```
I/flutter (10661): (2021-05-05 09:16:21.537513) ℹ️ 📡 Query channel start
I/flutter (10661): (2021-05-05 09:16:22.933288) ℹ️ 🔌 sending health.check
I/flutter (10661): (2021-05-05 09:16:25.104782) ℹ️ 📡 Got 5 channels from api
I/flutter (10661): (2021-05-05 09:16:25.131870) ℹ️ 📡 New Channel instance initialized created
I/flutter (10661): (2021-05-05 09:16:25.134213) ℹ️ 📡 New Channel instance initialized created
I/flutter (10661): (2021-05-05 09:16:25.136187) ℹ️ 📡 New Channel instance initialized created
I/flutter (10661): (2021-05-05 09:16:25.138029) ℹ️ 📡 New Channel instance initialized created
I/flutter (10661): (2021-05-05 09:16:25.139970) ℹ️ 📡 New Channel instance initialized created
```

And this is the log info when i create a new channel
```
I/flutter (10661): (2021-05-05 09:20:35.795159) ℹ️ 📡 handle new event: {type: notification.added_to_channel, cid: messaging:GAA__010, channel_id: GAA__010, channel_type: messaging, connection_id: null, created_at: 2021-05-05T02:20:36.761276Z, me: null, user: null, message: null, channel: {id: GAA__010, type: messaging, frozen: false, members: [
I/flutter (10661): (2021-05-05 09:20:35.808073) ℹ️ 🔌 received new event: {"type":"user.watching.start","cid":"messaging:GAA__010","channel_id":"GAA__010","channel_type":"messaging","user":{"id":"xxx","role":"user","created_at":"2021-04-19T03:35:33.29169Z","updated_at":"2021-04-19T06:09:20.59404Z","last_active":"2021-05-05T02:20:08.312476437Z","banned":false,"online":true,"invisible":false,"name":"xxx","unread_count":0},"watcher_count":1,"created_at":"2021-05-05T02:20:36.768185307Z"}
I/flutter (10661): (2021-05-05 09:20:35.809184) ℹ️ 📡 handle new event: {type: user.watching.start, cid: messaging:GAA__010, channel_id: GAA__010, channel_type: messaging, connection_id: null, created_at: 2021-05-05T02:20:36.768185Z, me: null, user: {id: xxx, invisible: false, name: xxx, unread_count: 0}, message: null, channel: null, member: null, reaction: null, total_unread_count: null, unread_channels: null, online: null, parent_id: null, is_local: false, watcher_count: 1}
I/flutter (10661): (2021-05-05 09:26:27.428745) ℹ️ 🔌 sending health.check
I/flutter (10661): (2021-05-05 09:26:27.932273) ℹ️ 🔌 received new event: {"type":"health.check","connection_id":"xxx","cid":"*","created_at":"2021-05-05T02:26:29.032415592Z"}
I/flutter (10661): (2021-05-05 09:26:27.933563) ℹ️ 📡 handle new event: {type: health.check, cid: *, channel_id: null, channel_type: null, connection_id: xxx, created_at: 2021-05-05T02:26:29.032415Z, me: null, user: null, message: null, channel: null, member: null, reaction: null, total_unread_count: null, unread_channels: null, online: null, parent_id: null, is_local: false}
```

**main.dart**
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  setupLocator();
  await Firebase.initializeApp();
  runApp(new MyApp());

  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'XxX',
        builder: (context, child) {
          return StreamChat(
            client: locator<ChatService>().client,
            child: child,
          );
        },
        home: Scaffold(resizeToAvoidBottomInset: true, body: LoginScreen()));
  }
}
```

**login.dart**
```
class LoginScreen extends StatefulWidget {
  @override
  _LoginScreenState createState() => new _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  
  @override
  void initState() {
    super.initState();
    getCredential();
  }

  getCredential() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    if (prefs.getString("userId") != null) {
      final client = locator<ChatService>().client;
      if (client.wsConnectionStatus != ConnectionStatus.connected) {
        await client.connectUser(
          User(
            id: prefs.getString("userId"),
            extraData: {
              'name': StringUtils.capitalize(prefs.getString("userName")),
            },
          ),
          prefs.getString("userToken"),
        );
      }
      setState(() {
        Navigator.pushReplacement(
          context,
          CupertinoPageRoute(builder: (context) => new HomeScreen()),
        );
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**home.dart**
```
class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => new _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.forum),
          backgroundColor: Color.fromRGBO(58, 66, 86, 1.0),
          onPressed: () {
            Navigator.push(
                context,
                new CupertinoPageRoute(
                    builder: (BuildContext context) => new ListChannel()));
          },
        ),
        body: Center()
    );
  }
}
```

**listchannel.dart**
```
class ListChannel extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        backgroundColor: Color.fromRGBO(5, 37, 17, 1),
        onPressed: () async {
          final client = locator<ChatService>().client;
          final channel = client.channel('messaging',
            id: '*IdYouWantToCreate*',
            extraData: {
              'name': 'name',
              'subtitle': 'subtitle',
              "members": [*YourIdMember*]
            });
            
          // await channel.create();
          await channel.watch();
        },
      ),
      appBar: new AppBar(title: Text("List Channel Diskusi")),
      body: ChannelsBloc(
        child: ChannelListView(
            filter: {
              // "type": "messaging",
              'members': {
                '\$in': [StreamChat.of(context).user.id],
              }
            },
            sort: [
              SortOption('last_message_at', direction: SortOption.DESC)
            ],
            options: {
              'state': true,
              'watch': true,
              'presence': true,
            },
            pagination: PaginationParams(limit: 50),
            channelPreviewBuilder: (context, channel) =>
                _channelPreviewBuilder(context, channel)),
      ),
    );
  }

  Widget _channelPreviewBuilder(BuildContext context, Channel channel) {
    var lastMessage, subtitle, lastText, opacity;
    var lastTime = "";
    subtitle = channel.extraData['subtitle'];
    if (channel.state.messages.length > 0) {
      lastMessage = channel.state.messages.reversed
          .firstWhere((message) => !message.isDeleted);
      lastText = "${lastMessage.user.name}: ${lastMessage.text}";
      var lastTimeMSE, date, now, today, yesterday, aDate;
      if (lastMessage.updatedAt != null) {
        lastTimeMSE = lastMessage.updatedAt.millisecondsSinceEpoch;
        date = DateTime.fromMillisecondsSinceEpoch(lastTimeMSE);
        now = DateTime.now();
        today = DateTime(now.year, now.month, now.day);
        yesterday = DateTime(now.year, now.month, now.day - 1);
        aDate = DateTime(date.year, date.month, date.day);
        if (aDate == today) {
          lastTime = DateFormat.Hm().format(date).toString();
        } else if (aDate == yesterday) {
          lastTime = "Yesterday";
        } else {
          lastTime = DateFormat('dd/MM/yy').format(date).toString();
        }
      }
      opacity = channel.state.unreadCount > .0 ? 1.0 : 0.5;
    } else {
      lastText = "";
      lastTime = "";
      opacity = 0.5;
    }

    return ListTile(
      contentPadding: EdgeInsets.symmetric(vertical: 10.0, horizontal: 15.0),
      title: ChannelName(
        textStyle:
            StreamChatTheme.of(context).channelPreviewTheme.title.copyWith(
                  color: Colors.black.withOpacity(opacity),
                ),
      ),
      subtitle: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: EdgeInsets.symmetric(vertical: 4.0),
            child: Text(
              subtitle,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          Text(
            lastText,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
        ],
      ),
      trailing: Container(
        width: 65.0,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Padding(
                padding: EdgeInsets.only(bottom: 5.0),
                child: Text(lastTime, style: TextStyle(fontSize: 12.0))),
            channel.state.unreadCount > 0
                ? CircleAvatar(
                    radius: 7,
                    backgroundColor: Colors.green,
                  )
                : Icon(Icons.check, size: 15.0),
          ],
        ),
      ),
      onTap: () async {
        await Navigator.of(context).push(
          CupertinoPageRoute(
            builder: (context) => StreamChannel(
              child: ChannelPage(channel: channel),
              channel: channel,
            ),
          ),
        );
      },
    );
  }
}
```

### PR DESCRIPTION
**Pull request by imtoori**
closes #413

### CODE REVIEW

**Comment by xsahil03x** [comment]
Better remove the automatic `loadData` logic from `channel_list_core` and handle them only in `channel_bloc`.
https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter_core/lib/src/channel_list_core.dart#L196

and `channel_bloc` logic should be changed to add new channels by default at the top and at the bottom if `lockChannelOrder` property is true.

https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat_flutter_core/lib/src/channels_bloc.dart#L150

**Comment by imtoori** [comment]
Actually, I think we should do these changes taking into consideration the fact that we have the comparator of the SortOptions and the filter objects, and we can sort channels as the user wants without additional code (apart from the comparators that may be mandatory)

That said, I think we could merge this fix and make other improvements more slowly in a different PR and task.

@xsahil03x thoughts?

File: packages/stream_chat_flutter_core/lib/src/channels_bloc.dart [hunk 1]
```diff
@@ -95,7 +95,12 @@ class ChannelsBlocState extends State<ChannelsBloc>
   }) async {
     final client = StreamChatCore.of(context).client;
 
-    if (_paginationEnded || _queryChannelsLoadingController.value == true) {
+    final clear = paginationParams == null ||
+        paginationParams.offset == null ||
+        paginationParams.offset == 0;
+
+    if ((!clear && _paginationEnded) ||
+        _queryChannelsLoadingController.value == true) {
```
Comment (xsahil03x) [inline packages/stream_chat_flutter_core/lib/src/channels_bloc.dart:103]: I don't think we really to do this for the fix

File: packages/stream_chat_flutter_core/lib/src/channels_bloc.dart [hunk 2]
```diff
@@ -148,7 +150,13 @@ class ChannelsBlocState extends State<ChannelsBloc>
     final client = StreamChatCore.of(context).client;
 
     if (!widget.lockChannelsOrder) {
-      _subscriptions.add(client.on(EventType.messageNew).listen((e) {
+      _subscriptions.add(client
+          .on(
+        EventType.messageNew,
+        EventType.notificationAddedToChannel,
+        EventType.notificationMessageNew,
```
Comment (xsahil03x) [inline packages/stream_chat_flutter_core/lib/src/channels_bloc.dart:157]: adding additional events are enough to solve this issue.

Comment (imtoori) [reply packages/stream_chat_flutter_core/lib/src/channels_bloc.dart:157]: We're already handling this event in ChannelListView, but the data is not being loaded because the pagination is ended.
This is the issue, and that happens also for the other events in that handler

File: packages/stream_chat_flutter_core/lib/src/channels_bloc.dart (hunk 1 above)
Comment (imtoori) [reply packages/stream_chat_flutter_core/lib/src/channels_bloc.dart:103]: https://github.com/GetStream/stream-chat-flutter/pull/414#discussion_r626516062

**Review by xsahil03x — APPROVED** [review]
LGTM
